### ISSUE TITLE
决策表少字段[strategy_type]

### ISSUE THREAD

**Issue by Ytors** [DingQianWen/rule-engine#4]
![image](https://user-images.githubusercontent.com/19896526/103860024-06ba9480-50f6-11eb-8767-dabafb53655c.png)

**Comment by DingQianWen** [comment]
你好，目前最新的数据库表数据已经上传，在rule-engine\rule-engine-web\src\main\resources\sql\boot_engine.sql目录下，请拉取代码

**Comment by Ytors** [comment]
感谢
